version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pg1234
            PGDATA: /var/lib/postgresql/data
        ports: 
            - 3000:5432